// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwxfqtqqrndymyqlkvbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3eGZxdHFxcm5keW15cWxrdmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDA5MjcsImV4cCI6MjA2NDExNjkyN30.0RdF6kz-ehNZwXQWbVcUq5lWNG4OJKVFzh5jakS34zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);